<div class="container">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Mail</th>
            <th>Display Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user):?>
            <tr>
                <td><?php echo $user->getId(); ?></td>
                <td><?php echo $user->getUsername(); ?></td>
                <td><?php echo $user->getEmail(); ?></td>
                <td><?php echo $user->getDisplayName(); ?></td>
                <td>
                    <?php
                    $urlEdit = $this->url('zfcadmin/user', array('action' => 'edit', 'id' =>$user->getId()));
                    $urlDelete = $this->url('zfcadmin/user', array('action' => 'delete', 'id' =>$user->getId()));
                    ?>
                    <a href="<?php echo $urlEdit;?>"><i class="fam-pencil"></i></a>
                    <a href="<?php echo $urlDelete;?>"><i class="fam-delete"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
    <!--    --><?php //echo $this->paginationControl($this->paginator, 'Sliding', 'paginator'); ?>
</div>