<div class="container">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Titre</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Rôle</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user):?>
            <tr>
                <td><?php echo $user->user_id; ?></td>
                <td><?php echo $user->username; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->lastname; ?></td>
                <td><?php echo $user->type; ?></td>
                <td>
                    <?php
                    $urlDelete = $this->url('zfcadmin/user', array('action' => 'delete', 'id' => $user->user_id), null, false);
                    ?>
                    <a href="<?php echo $urlDelete;?>"><i class="fam-delete"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<!--    --><?php //echo $this->paginationControl($this->paginator, 'Sliding', 'paginator'); ?>
</div>