<div class="table-wrapper">
    <h4><a href="<?= $this->url('zfcadmin/tag', array('action' => 'add'),null, false);?>"><i class="fam-add"></i>Ajouter un tag</a></h4>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Nom</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($tags as $tag):?>
            <tr>
                <td><?php echo $tag->tag_id; ?></td>
                <td><?php echo $tag->name; ?></td>
                <td>
                    <?php
                    $urlEdit = $this->url('zfcadmin/tag', array('action' => 'edit', 'id' => $tag->tag_id), null, false);
                    $urlDelete = $this->url('zfcadmin/tag', array('action' => 'delete', 'id' => $tag->tag_id), null, false);
                    ?>
                    <a href="<?php echo $urlEdit;?>"><i class="fam-pencil"></i></a>
                    <a href="<?php echo $urlDelete;?>"><i class="fam-delete"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<!-- <?php //echo $this->paginationControl($this->paginator, 'Sliding', 'paginator'); ?> -->
</div>