<div id="content">
    <?php foreach ($posts as $entry): ?>
        <div id="<?= $entry->id ?>" class="post">
            <p class="meta">
            <h1><?= $entry->title ?></h1>
            <span class="posted">Posted by <a href="#"><?= $entry->author ?></a></span>
            </p>
            <div style="clear: both;">&nbsp;</div>
            <div class="entry">
                <p><?= $entry->content ?></p>
                <p class="links"><a href="<?= $this->url('list_post_page', array('action' => 'show', 'id' =>$entry->id)); ?>">En savoir plus</a></p>
            </div>
        </div>
    <?php endforeach; ?>
    <div style="clear: both;">&nbsp;</div>
</div>
<!-- end #content -->