<div id="content">
    <div class="post">
        <p class="meta">
        <h1><?= $post->title ?> </h1>
        <span class="posted">Posted by <a href="#"><?= $post->author ?></a></span>
        </p>
        <div style="clear: both;">&nbsp;</div>
        <div class="entry">
            <p><?= $post->content ?></p>
        </div>
    </div>
    <div style="clear: both;">&nbsp;</div>
</div>
<!-- end #content -->