<!-- Main -->
<div id="main">
    <!-- Post -->
    <article id="<?= $post->id ?>" class="post">
        <header>
            <div class="title">
                <h2><a href="#"><?= $post->title ?></a></h2>
                <p></p>
            </div>
            <div class="meta">
                <time class="published" datetime="2015-11-01">November 1, 2015</time>
                <a href="#" class="author"><span class="name"><?= $post->author ?></span><img src="/img/avatar.jpg" alt="" /></a>
            </div>
        </header>
        <a href="#" class="image featured"><img src="/img/pic01.jpg" alt="" /></a>
        <p><?= $post->content ?></p>
        <footer>
            <ul class="stats">
                <li><a href="#"><?= $post->category ?></a></li>
                <li><a href="#" class="icon fa-heart">28</a></li>
                <li><a href="#" class="icon fa-comment">128</a></li>
            </ul>
        </footer>
    </article>
</div>