<?php
$title = 'Ajouter un article';
$this->headTitle($title);
?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/post/action', array('action' => 'edit', 'id' => $form->get('post_id')->getValue())));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('post_id'));
//echo $this->formHidden($form->get('csrf'));

?>

    <div class="control-group">
        <?php echo $this->formLabel($form->get('title')->setLabelAttributes(array('class' => 'control-label')));?>
        <div class="controls">
            <?php echo $this->formText($form->get('title'));?>
            <?php echo $this->formElementErrors($form->get('title'), array('class' => 'error_list'));?>
        </div>
    </div>

    <div class="control-group">
        <?php echo $this->formLabel($form->get('content')->setLabelAttributes(array('class' => 'control-label')));?>
        <div class="controls">
            <?php echo $this->formTextarea($form->get('content'));?>
            <?php echo $this->formElementErrors($form->get('content'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('author')->setLabelAttributes(array('class' => 'control-label')));?>
        <div class="controls">
            <?php echo $this->formText($form->get('author'));?>
            <?php echo $this->formElementErrors($form->get('author'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="control-group">
        <?php echo $this->formLabel($form->get('category')->setLabelAttributes(array('class' => 'control-label')));?>
        <div class="controls">
            <?php echo $this->formSelect($form->get('category'));?>
            <?php echo $this->formElementErrors($form->get('category'), array('class' => 'error_list'));?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <?php echo $this->formSubmit($form->get('submit'), array('class' => 'btn'));?>
        </div>
    </div>
<?php
echo $this->form()->closeTag();
?>