<?php
$title = 'Ajouter un article';
$this->headTitle($title);
?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/post', array('action' => 'edit', 'id' => $form->get('post_id')->getValue())));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('post_id'));
//echo $this->formHidden($form->get('csrf'));

?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('title')->setLabelAttributes(array('class' => 'col-sm-2 control-label')));?>
        <div class="col-sm-10">
            <?php echo $this->formText($form->get('title')->setLabelAttributes(array('class' => 'form-control')));?>
            <?php echo $this->formElementErrors($form->get('title'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('content')->setLabelAttributes(array('class' => 'col-sm-2 control-label')));?>
        <div class="col-sm-10">
            <?php echo $this->formTextarea($form->get('content')->setLabelAttributes(array('class' => 'form-control')));?>
            <?php echo $this->formElementErrors($form->get('content'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('author')->setLabelAttributes(array('class' => 'col-sm-2 control-label')));?>
        <div class="col-sm-10">
            <?php echo $this->formText($form->get('author')->setLabelAttributes(array('class' => 'form-control')));?>
            <?php echo $this->formElementErrors($form->get('author'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('category_id')->setLabelAttributes(array('class' => 'col-sm-2 control-label')));?>
        <div class="col-sm-10 select-wrapper">
            <?php echo $this->formSelect($form->get('category_id')->setLabelAttributes(array('class' => 'form-control')));?>
            <?php echo $this->formElementErrors($form->get('category_id'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('tags')->setLabelAttributes(array('class' => 'col-sm-2')));?>
        <div class="col-sm-10 checkbox">
            <?php echo $this->formMulticheckbox($form->get('tags'));?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formSubmit($form->get('submit'), array('class' => 'btn'));?>
        </div>
    </div>
<?php
echo $this->form()->closeTag();
?>