<div class="table-wrapper">
    <h4><a href="<?= $this->url('zfcadmin/post', array('action' => 'add'),null, false);?>"><i class="fam-add"></i>Nouvelle article</a></h4>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Titre</th>
            <th>Catégorie</th>
            <th>Contenue</th>
            <th>Auteur</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($posts as $post):?>
            <tr>
                <td><?php echo $post->post_id; ?></td>
                <td><a href="<?php echo $this->url('list_post_page', array('action' => 'show', 'id' => $post->post_id)); ?>"><?php echo $post->title; ?></a></td>
                <td><?php echo $post->category->name; ?></td>
                <td><?php echo $post->content; ?></td>
                <td><?php echo $post->author->getDisplayName(); ?></td>
                <td>
                    <?php
                    $urlEdit = $this->url('zfcadmin/post', array('action' => 'edit', 'id' => $post->post_id), null, false);
                    $urlDelete = $this->url('zfcadmin/post', array('action' => 'delete', 'id' => $post->post_id), null, false);
                    ?>
                    <a href="<?php echo $urlEdit;?>"><i class="fam-pencil"></i></a>
                    <a href="<?php echo $urlDelete;?>"><i class="fam-delete"></i></a>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
<!--    --><?php //echo $this->paginationControl($this->paginator, 'Sliding', 'paginator'); ?>
</div>