<?php echo $this->doctype(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Guettapen</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/css/main.css" />
    <!--[if lte IE 9]><link rel="stylesheet" href="/css/ie9.css" /><![endif]-->
    <!--[if lte IE 8]><link rel="stylesheet" href="/css/ie8.css" /><![endif]-->
</head>
<body>

<!-- Wrapper -->
<div id="wrapper">

    <!-- Header -->
    <header id="header">
        <h1><a href="#">GUETTAPEN</a></h1>
        <nav class="links">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/category/news/page/1">News</a></li>
                <li><a href="/category/music/page/1">Music</a></li>
                <li><a href="/category/events/page/1">Events</a></li>
                <?php if($this->zfcUserIdentity()): ?>
                    <li><a href="<?= $this->url('zfcadmin'); ?>">Administration</a></li>
                    <li><a href="<?= $this->url('zfcuser/logout'); ?>">Déconnexion</a></li>
                    <div style="float:right; margin-right:15px"> Bonjour <?php echo $this->zfcUserIdentity()->getDisplayname(); ?> ! </div>

                <?php endif?>
            </ul>
        </nav>
        <nav class="main">
            <ul>
                <li class="search">
                    <a class="fa-search" href="#search">Rechercher</a>
                    <form id="search" method="get" action="#">
                        <input type="text" name="query" placeholder="Search" />
                    </form>
                </li>
                <li class="menu">
                    <a class="fa-bars" href="#menu">Menu</a>
                </li>
            </ul>
        </nav>
    </header>

    <!-- Menu -->
    <section id="menu">

        <!-- Search -->
        <section>
            <form class="search" method="get" action="#">
                <input type="text" name="query" placeholder="Rechercher" />
            </form>
        </section>

        <!-- Links -->
        <section>
            <ul class="links">
                <li>
                    <a href="#">
                        <h3>Lorem ipsum</h3>
                        <p>Feugiat tempus veroeros dolor</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <h3>Dolor sit amet</h3>
                        <p>Sed vitae justo condimentum</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <h3>Feugiat veroeros</h3>
                        <p>Phasellus sed ultricies mi congue</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <h3>Etiam sed consequat</h3>
                        <p>Porta lectus amet ultricies</p>
                    </a>
                </li>
            </ul>
        </section>

        <!-- Actions -->
        <section>
            <ul class="actions vertical">
                <?php if(!$this->zfcUserIdentity()): ?>
                    <!-- display the login form -->
                    <li><a href="<?= $this->url('zfcuser_login'); ?>" class="button big fit">Se connecter</a></li>
                <?php else: ?>
                    <!-- display the 'display name' of the user -->
                    <li><a href="<?= $this->url('zfcadmin'); ?>" class="button big fit">Administration</a></li>
                <?php endif?>
            </ul>
        </section>

    </section>

    <?php
        if (isset($ourView->flashMessages) && count($ourView->flashMessages)):?>
            <?php foreach ($ourView->flashMessages as $messages):?>
                <?php foreach ($messages as $key => $message):?>
                    <div class="alert alert-<?php echo $key;?>">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <?php echo $message;?>
                    </div>
                <?php endforeach;?>
            <?php endforeach;?>
        <?php endif; ?>

    <?php  echo $this->content; ?>

    <!-- Sidebar -->
    <section id="sidebar">

        <!-- Intro -->
        <section id="intro">
            <a href="#" class="logo"><img src="/img/logo.png" alt="" /></a>
            <header>
                <h2>GUETTAPEN</h2>
                <p>La Musique Electronique. Autrement.</p>
            </header>
        </section>

        <!-- Mini Posts -->
<!--        <section>-->
<!--            <div class="mini-posts">-->
<!---->
                <!-- Mini Post -->
<!--                <article class="mini-post">-->
<!--                    <header>-->
<!--                        <h3><a href="#">Vitae sed condimentum</a></h3>-->
<!--                        <time class="published" datetime="2015-10-20">October 20, 2015</time>-->
<!--                        <a href="#" class="author"><img src="/img/avatar.jpg" alt="" /></a>-->
<!--                    </header>-->
<!--                    <a href="#" class="image"><img src="/img/pic04.jpg" alt="" /></a>-->
<!--                </article>-->
<!---->
                <!-- Mini Post -->
<!--                <article class="mini-post">-->
<!--                    <header>-->
<!--                        <h3><a href="#">Rutrum neque accumsan</a></h3>-->
<!--                        <time class="published" datetime="2015-10-19">October 19, 2015</time>-->
<!--                        <a href="#" class="author"><img src="/img/avatar.jpg" alt="" /></a>-->
<!--                    </header>-->
<!--                    <a href="#" class="image"><img src="/img/pic05.jpg" alt="" /></a>-->
<!--                </article>-->
<!---->
                <!-- Mini Post -->
<!--                <article class="mini-post">-->
<!--                    <header>-->
<!--                        <h3><a href="#">Odio congue mattis</a></h3>-->
<!--                        <time class="published" datetime="2015-10-18">October 18, 2015</time>-->
<!--                        <a href="#" class="author"><img src="/img/avatar.jpg" alt="" /></a>-->
<!--                    </header>-->
<!--                    <a href="#" class="image"><img src="/img/pic06.jpg" alt="" /></a>-->
<!--                </article>-->
<!---->
                <!-- Mini Post -->
<!--                <article class="mini-post">-->
<!--                    <header>-->
<!--                        <h3><a href="#">Enim nisl veroeros</a></h3>-->
<!--                        <time class="published" datetime="2015-10-17">October 17, 2015</time>-->
<!--                        <a href="#" class="author"><img src="/img/avatar.jpg" alt="" /></a>-->
<!--                    </header>-->
<!--                    <a href="#" class="image"><img src="/img/pic07.jpg" alt="" /></a>-->
<!--                </article>-->
<!---->
<!--            </div>-->
<!--        </section>-->

        <!-- Category List -->
        <section>
            <h2>Catégories</h2>
            <?= $this->widgetCategory(); ?>
        </section>

        <!-- Tag List -->
        <section>
            <h2>Tags</h2>
            <?= $this->widgetTag(); ?>
        </section>

        <!-- About -->
<!--        <section class="blurb">-->
<!--            <h2>About</h2>-->
<!--            <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>-->
<!--            <ul class="actions">-->
<!--                <li><a href="#" class="button">Learn More</a></li>-->
<!--            </ul>-->
<!--        </section>-->

        <!-- Footer -->
        <section id="footer">
            <ul class="icons">
                <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
                <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
        </section>

    </section>

</div>

<!-- Scripts -->
<script src="/js/jquery.min.js"></script>
<script src="/js/skel.min.js"></script>
<script src="/js/util.js"></script>
<!--[if lte IE 8]><script src="/js/ie/respond.min.js"></script><![endif]-->
<script src="/js/main.js"></script>

</body>
</html>