<?php
$title = 'Ajouter une catégorie';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('add_category', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('category_id'));
echo $this->formRow($form->get('nom'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();