<?php
$title = 'Ajouter une catégorie';
$this->headTitle($title);
?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/category', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('category_id'));
//echo $this->formHidden($form->get('csrf'));

?>
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')->setLabelAttributes(array('class' => 'col-sm-2 control-label')));?>
        <div class="col-sm-10">
            <?php echo $this->formText($form->get('name')->setLabelAttributes(array('class' => 'form-control')));?>
            <?php echo $this->formElementErrors($form->get('name'), array('class' => 'error_list'));?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formSubmit($form->get('submit'), array('class' => 'btn'));?>
        </div>
    </div>
<?php
echo $this->form()->closeTag();
?>