<div id="content">
	<?php foreach ($posts as $post): ?>
		<h1><?= $this->escapeHtml($post->author) ?></h1>
	<div class="post">
		<p class="meta">
			<h1><?= $this->escapeHtml($post->title) ?> </h1>
			<span class="posted">Posted by <a href="#"><?= $this->escapeHtml($post->author) ?></a></span>
		</p>
		<div style="clear: both;">&nbsp;</div>
		<div class="entry">
			<p><?= $this->escapeHtml($post->content) ?></p>
			<p class="links"><a href="#">Read More</a></p>
		</div>
	</div>
	<?php endforeach; ?>
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end #content -->