
<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="/admin/category"><i class="fam-cog"></i> Catégories</a>
        </div>
        <div class="span9">
            Gestion des catégories
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/admin/post"><i class="fam-page"></i> Articles</a>
        </div>
        <div class="span9">
            Gestion des articles
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/admin/users"><i class="fam-user"></i> Utilisateurs</a>
        </div>
        <div class="span9">
            Gestion des utilisateurs
        </div>
    </div>
</div>