
<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="/admin/category/1"><i class="fam-cog"></i> Catégories</a>
        </div>
        <div class="span9">
            Gestion des catégories
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/admin/post/1"><i class="fam-page"></i> Articles</a>
        </div>
        <div class="span9">
            Gestion des articles
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/admin/user/1"><i class="fam-user"></i> Utilisateurs</a>
        </div>
        <div class="span9">
            Gestion des utilisateurs
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/admin/comment/1"><i class="fam-user"></i> Commentaires</a>
        </div>
        <div class="span9">
            Gestion des commentaires
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/admin/tag/1"><i class="fam-user"></i> Tags</a>
        </div>
        <div class="span9">
            Gestion des tags
        </div>
    </div>
    <hr />
</div>